const users = [
  {
    name: 'Tedi',
    username: 'tedi',
    password: '123',
    imageUrl: '',
    address: '134 Maple Ave, Milwaukee, WI',
  },
  {
    name: 'Kwame',
    username: 'kwame',
    password: '123',
    imageUrl: '',
    address: '145 W Walnut St, Milwaukee, WI',
  },
  {
    name: 'Sulaiman',
    username: 'sulaiman',
    password: '123',
    imageUrl: '',
    address: '123 Walnut St, Milwaukee, WI',
  },
  {
    name: 'Konstantin',
    username: 'konstantin',
    password: '123',
    imageUrl: '',
    address: '156 Ash St, Milwaukee, WI',
  },
  {
    name: 'Bob',
    username: 'bobsyourneighbor',
    password: 'bobrocks',
    imageUrl: '',
    address: '',
  },
  {
    name: 'Susan',
    username: 'soccermom34',
    password: 'go0o0o0al',
    imageUrl: '',
    address: '',
  },
  {
    name: 'Peter',
    username: 'musicianpete',
    password: 'beethoven13th',
    imageUrl: '',
    address: '',
  },
  {
    name: 'Cheryl',
    username: 'momof3',
    password: 'password',
    imageUrl: '',
    address: '',
  },
  {
    name: 'Tim',
    username: 'itstim',
    password: 'fisher45',
    imageUrl: '',
    address: '',
  },
  {
    name: 'Sean',
    username: 'purepositivity',
    password: 'whiskeyincoffee',
    imageUrl: '',
    address: '',
  },
  {
    name: 'Jibron',
    username: 'oshawattenthusiast',
    password: 'saurottsucks',
    imageUrl: '',
    address: '',
  },
  {
    name: 'Bart',
    username: 'bartbot',
    password: '1011011',
    imageUrl: '',
    address: '',
  },
];
module.exports = users;
